import { PLAN_DURATIONS, planDaysToPaidMonths } from '@/lib/constants';
import { addDaysToIsoDate, getTodayDateParts } from '@/utils/date';

const shiftDate = (parts, dayOffset) => {
  const utc = Date.UTC(parts.year, parts.month - 1, parts.day + dayOffset);
  const date = new Date(utc);
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, '0');
  const day = String(date.getUTCDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

const today = getTodayDateParts();

/**
 * Sample members shaped like the `members` table in docs/06-supabase.md.
 * Dates are computed relative to "today" so active / expiring / expired states stay visible.
 */
export const INITIAL_MOCK_MEMBERS = [
  {
    id: '11111111-1111-4111-8111-111111111111',
    full_name: 'Aarav Sharma',
    phone_number: '9876543210',
    email: 'aarav.sharma@email.com',
    gender: 'male',
    date_of_birth: '1996-04-12',
    address: 'Sector 14, Noida',
    selfie_url: null,
    plan_type: 'monthly',
    plan_duration_days: PLAN_DURATIONS.monthly,
    plan_start_date: shiftDate(today, -10),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.monthly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -10), PLAN_DURATIONS.monthly),
    plan_amount: 1500,
    payment_status: 'paid',
    notes: 'Prefers evening slots',
    created_at: `${shiftDate(today, -10)}T08:00:00.000Z`,
    updated_at: `${shiftDate(today, -10)}T08:00:00.000Z`,
  },
  {
    id: '22222222-2222-4222-8222-222222222222',
    full_name: 'Priya Verma',
    phone_number: '9811122233',
    email: 'priya.verma@email.com',
    gender: 'female',
    date_of_birth: '1994-08-21',
    address: 'Indirapuram, Ghaziabad',
    selfie_url: null,
    plan_type: 'quarterly',
    plan_duration_days: PLAN_DURATIONS.quarterly,
    plan_start_date: shiftDate(today, -87),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.quarterly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -87), PLAN_DURATIONS.quarterly),
    plan_amount: 4000,
    payment_status: 'paid',
    notes: '',
    created_at: `${shiftDate(today, -87)}T09:30:00.000Z`,
    updated_at: `${shiftDate(today, -20)}T09:30:00.000Z`,
  },
  {
    id: '33333333-3333-4333-8333-333333333333',
    full_name: 'Rohan Mehta',
    phone_number: '9822334455',
    email: null,
    gender: 'male',
    date_of_birth: '1990-01-05',
    address: 'Vaishali, Ghaziabad',
    selfie_url: null,
    plan_type: 'monthly',
    plan_duration_days: PLAN_DURATIONS.monthly,
    plan_start_date: shiftDate(today, -28),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.monthly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -28), PLAN_DURATIONS.monthly),
    plan_amount: 1500,
    payment_status: 'pending',
    notes: 'Asked about personal training',
    created_at: `${shiftDate(today, -28)}T11:00:00.000Z`,
    updated_at: `${shiftDate(today, -2)}T11:00:00.000Z`,
  },
  {
    id: '44444444-4444-4444-8444-444444444444',
    full_name: 'Neha Kapoor',
    phone_number: '9898989898',
    email: 'neha.k@email.com',
    gender: 'female',
    date_of_birth: '1998-11-30',
    address: 'Kaushambi',
    selfie_url: null,
    plan_type: 'yearly',
    plan_duration_days: PLAN_DURATIONS.yearly,
    plan_start_date: shiftDate(today, -200),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.yearly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -200), PLAN_DURATIONS.yearly),
    plan_amount: 12000,
    payment_status: 'paid',
    notes: '',
    created_at: `${shiftDate(today, -200)}T07:15:00.000Z`,
    updated_at: `${shiftDate(today, -200)}T07:15:00.000Z`,
  },
  {
    id: '55555555-5555-4555-8555-555555555555',
    full_name: 'Vikram Singh',
    phone_number: '9765432109',
    email: 'vikram.singh@email.com',
    gender: 'male',
    date_of_birth: '1988-06-18',
    address: 'Raj Nagar Extension',
    selfie_url: null,
    plan_type: 'half_yearly',
    plan_duration_days: PLAN_DURATIONS.half_yearly,
    plan_start_date: shiftDate(today, -190),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.half_yearly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -190), PLAN_DURATIONS.half_yearly),
    plan_amount: 7000,
    payment_status: 'paid',
    notes: 'Expired — follow up for renewal',
    created_at: `${shiftDate(today, -190)}T10:00:00.000Z`,
    updated_at: `${shiftDate(today, -5)}T10:00:00.000Z`,
  },
  {
    id: '66666666-6666-4666-8666-666666666666',
    full_name: 'Ananya Gupta',
    phone_number: '9900112233',
    email: 'ananya.g@email.com',
    gender: 'female',
    date_of_birth: '2001-02-14',
    address: 'Crossing Republik',
    selfie_url: null,
    plan_type: 'monthly',
    plan_duration_days: PLAN_DURATIONS.monthly,
    plan_start_date: shiftDate(today, -29),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.monthly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -29), PLAN_DURATIONS.monthly),
    plan_amount: 1500,
    payment_status: 'paid',
    notes: '',
    created_at: `${shiftDate(today, -29)}T12:45:00.000Z`,
    updated_at: `${shiftDate(today, -29)}T12:45:00.000Z`,
  },
  {
    id: '77777777-7777-4777-8777-777777777777',
    full_name: 'Karan Malhotra',
    phone_number: '9123456780',
    email: null,
    gender: 'male',
    date_of_birth: '1995-09-09',
    address: 'Shipra Mall Road',
    selfie_url: null,
    plan_type: 'quarterly',
    plan_duration_days: PLAN_DURATIONS.quarterly,
    plan_start_date: shiftDate(today, -40),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.quarterly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -40), PLAN_DURATIONS.quarterly),
    plan_amount: 4000,
    payment_status: 'paid',
    notes: 'Morning batch regular',
    created_at: `${shiftDate(today, -40)}T06:20:00.000Z`,
    updated_at: `${shiftDate(today, -40)}T06:20:00.000Z`,
  },
  {
    id: '88888888-8888-4888-8888-888888888888',
    full_name: 'Sana Ali',
    phone_number: '9988776655',
    email: 'sana.ali@email.com',
    gender: 'female',
    date_of_birth: '1997-07-07',
    address: 'Vasundhara',
    selfie_url: null,
    plan_type: 'monthly',
    plan_duration_days: PLAN_DURATIONS.monthly,
    plan_start_date: shiftDate(today, -45),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.monthly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -45), PLAN_DURATIONS.monthly),
    plan_amount: 1500,
    payment_status: 'pending',
    notes: 'Needs payment confirmation',
    created_at: `${shiftDate(today, -45)}T14:00:00.000Z`,
    updated_at: `${shiftDate(today, -1)}T14:00:00.000Z`,
  },
  {
    id: '99999999-9999-4999-8999-999999999999',
    full_name: 'Aditya Rao',
    phone_number: '9876501234',
    email: 'aditya.rao@email.com',
    gender: 'male',
    date_of_birth: '1993-12-01',
    address: 'Indirapuram',
    selfie_url: null,
    plan_type: 'yearly',
    plan_duration_days: PLAN_DURATIONS.yearly,
    plan_start_date: shiftDate(today, -30),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.yearly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -30), PLAN_DURATIONS.yearly),
    plan_amount: 12000,
    payment_status: 'paid',
    notes: 'Joined via QR registration',
    created_at: `${shiftDate(today, -30)}T16:10:00.000Z`,
    updated_at: `${shiftDate(today, -30)}T16:10:00.000Z`,
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    full_name: 'Meera Iyer',
    phone_number: '9812345678',
    email: 'meera.iyer@email.com',
    gender: 'female',
    date_of_birth: '1999-03-22',
    address: 'Noida Extension',
    selfie_url: null,
    plan_type: 'half_yearly',
    plan_duration_days: PLAN_DURATIONS.half_yearly,
    plan_start_date: shiftDate(today, -60),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.half_yearly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -60), PLAN_DURATIONS.half_yearly),
    plan_amount: 7000,
    payment_status: 'paid',
    notes: '',
    created_at: `${shiftDate(today, -60)}T08:40:00.000Z`,
    updated_at: `${shiftDate(today, -60)}T08:40:00.000Z`,
  },
  {
    id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    full_name: 'Harsh Patel',
    phone_number: '9700011223',
    email: null,
    gender: 'male',
    date_of_birth: '1992-05-16',
    address: 'Ghaziabad',
    selfie_url: null,
    plan_type: 'monthly',
    plan_duration_days: PLAN_DURATIONS.monthly,
    plan_start_date: shiftDate(today, -27),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.monthly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -27), PLAN_DURATIONS.monthly),
    plan_amount: 1500,
    payment_status: 'paid',
    notes: 'Expiring soon',
    created_at: `${shiftDate(today, -27)}T09:00:00.000Z`,
    updated_at: `${shiftDate(today, -27)}T09:00:00.000Z`,
  },
  {
    id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    full_name: 'Ishita Banerjee',
    phone_number: '9654321098',
    email: 'ishita.b@email.com',
    gender: 'female',
    date_of_birth: '2000-10-10',
    address: 'Rajendra Nagar',
    selfie_url: null,
    plan_type: 'quarterly',
    plan_duration_days: PLAN_DURATIONS.quarterly,
    plan_start_date: shiftDate(today, -100),
    paid_duration_months: planDaysToPaidMonths(PLAN_DURATIONS.quarterly),
    current_period_end: addDaysToIsoDate(shiftDate(today, -100), PLAN_DURATIONS.quarterly),
    plan_amount: 4000,
    payment_status: 'paid',
    notes: 'Returning after break',
    created_at: `${shiftDate(today, -100)}T13:25:00.000Z`,
    updated_at: `${shiftDate(today, -3)}T13:25:00.000Z`,
  },
];
